name: Auto-merge dependency updates
on:
  workflow_call:
    secrets:
      github-token:
        required: true
jobs:
  merge:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.actor.login == 'dependabot[bot]'
    steps:
    - name: Find associated pull request
      id: pr
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
      with:
        script: |
          const response = await github.rest.search.issuesAndPullRequests({
            q: 'repo:${{ github.repository }} is:pr sha:${{ github.event.workflow_run.head_sha }}',
            per_page: 1,
          })
          const items = response.data.items
          if (items.length < 1) {
            console.error('No PRs found')
            return
          }
          const pullRequestNumber = items[0].number
          console.info("Pull request number is", pullRequestNumber)
          return pullRequestNumber
    - run: 'gh pr merge --auto --squash https://github.com/$GITHUB_REPOSITORY/pull/$GITHUB_PR'
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
        GITHUB_PR: ${{ steps.pr.outputs.result }}
