name: Sync GitHub issues to Jira
on:
  workflow_call:
    secrets:
      jira-base-url:
        required: true
      jira-api-token:
        required: true
      github-token:
        required: true
    inputs:
      issue_label:
        required: false
        type: string
jobs:
  open:
    if: github.event.action == 'opened'
    runs-on: ubuntu-22.04
    name: Create new tickets in Jira
    permissions:
      issues: write
    steps:
    - name: Login
      uses: acquia/gajira-login@bearer
      env:
        JIRA_BASE_URL: ${{ secrets.jira-base-url }}
        JIRA_API_TOKEN: ${{ secrets.jira-api-token }}
    - name: Set issue type
      id: issue_type
      run: |
        case $ISSUE_LABEL in
          bug)
            echo "type=Bug" >> $GITHUB_OUTPUT
            ;;
          enhancement)
            echo "type=Story" >> $GITHUB_OUTPUT
            ;;
          support)
            echo "type=Priority Support" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "type=Task" >> $GITHUB_OUTPUT
            ;;
          esac
      env:
        ISSUE_LABEL: ${{ github.event.issue.labels[0].name }}
    - name: Get project key
      id: project_key
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: |
        echo "key=${GITHUB_REPOSITORY_NAME^^}" >> $GITHUB_OUTPUT
    - name: Set fields
      id: set_fields
      run: |
        echo "fields={\"labels\":[\"$ISSUE_LABEL\"]}" >> $GITHUB_OUTPUT
      env:
        ISSUE_LABEL: ${{ inputs.issue_label }}
    - name: Create
      id: create
      uses: acquia/gajira-create@bearer
      with:
        project: ${{ steps.project_key.outputs.key }}
        issuetype: ${{ steps.issue_type.outputs.type }}
        summary: ${{ github.event.issue.title }}
        description: ${{ github.event.issue.html_url }}
        fields: ${{ steps.set_fields.outputs.fields }}
    - name: Update Github issue with Jira ticket prefix
      run: 'gh issue edit $GH_ISSUE --title "$JIRA_ISSUE: $ISSUE_TITLE"'
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
        GH_ISSUE: ${{ github.event.issue.html_url }}
        JIRA_ISSUE: ${{ steps.create.outputs.issue }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
  close:
    if: github.event.action == 'closed'
    runs-on: ubuntu-22.04
    name: Comment in Jira
    permissions:
      issues: write
    steps:
      - name: Get project key
        id: project_key
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: |
          echo "key=${GITHUB_REPOSITORY_NAME^^}" >> $GITHUB_OUTPUT
      - name: Get Jira issue
        id: get-issue
        run: |
          if [[ "$ISSUE_TITLE" =~ ^($PROJECT_KEY-[0-9]+): ]]; then
              echo "issue=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          PROJECT_KEY: ${{ steps.project_key.outputs.key }}
      - name: Login
        if: steps.get-issue.outputs.issue
        uses: acquia/gajira-login@bearer
        env:
          JIRA_BASE_URL: ${{ secrets.jira-base-url }}
          JIRA_API_TOKEN: ${{ secrets.jira-api-token }}
      - name: Comment
        if: steps.get-issue.outputs.issue
        uses: acquia/gajira-comment@bearer
        with:
          issue: ${{ steps.get-issue.outputs.issue }}
          comment: The GitHub issue corresponding to this ticket has been closed
